---
title: "Data analysis for FDR regression"
author: "Simina Boca, Jeff Leek"
date: "December 30, 2015"
VignetteBuilder: knitr
Suggests: BiocStyle, knitr, rmarkdown
output:
    BiocStyle::html_document:
    toc: true
---

<!--
%% \VignetteEngine{knitr::rmarkdown}
-->

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path='Figures/')
```

```{r style, echo = FALSE, results = 'asis'}
BiocStyle::markdown()
```

### Load the relevant libraries

```{r,message=FALSE}
library(readr)
library(dplyr)
library(fdrtool)
library(betareg)
library(splines)
library(Hmisc)
library(ggplot2)
```


### Load the data (first need to download the file from https://www.broadinstitute.org/collaboration/giant/index.php/GIANT_consortium_data_files#GWAS_Anthropometric_2015_BMI)

```{r,cache=TRUE}
tot = read_tsv("All_ancestries_SNP_gwas_mc_merge_nogc.tbl.uniq")
dim(tot)

lambda <- 0.8
tot = mutate(tot,y = p > lambda) ##this adds a new variable which is TRUE is p > 0.9, FALSE otherwise
tot = filter(tot,!is.na(Freq1.Hapmap))
dim(tot)
##change the frequency to the minor allele frequency
tot$Freq1.Hapmap[tot$Freq1.Hapmap > 0.5] <- 1-tot$Freq1.Hapmap[tot$Freq1.Hapmap > 0.5]
tot = mutate(tot,freq=cut2(Freq1.Hapmap,g=3)) ##added a new variable with frequency intervals for HapMap CEU frequencies
table(tot$freq)
```

### Estimate covariate-specific pi0

```{r,cache=TRUE}
lm1 = lm(y ~ ns(N,df=5) + freq,data=tot)
##range(lm1$fitted)
tot = data.frame(tot,fitted=lm1$fitted/(1-lambda)) ##fitted represents the probability of being from the null, i.e. of no association with BMI
range(tot$fitted)
tot = mutate(tot,fitted=ifelse(fitted > 1, 1, fitted))
range(tot$fitted)

##get random sample of 50,000 SNPs
set.seed(310841)
d1 = tot %>% sample_n(5e4)

##how many SNPs have N < 200,000?
sum(tot$N < 200000)
```

### Make figures

```{r Fig3,cache=TRUE, fig.width=9, fig.height=5}
par(mfrow=c(1,2))
hist(tot$p, col="grey", main="All N", xlab="P-value")
hist(tot$p[tot$N < 200000], col="grey", main="N < 200,000", xlab="P-value")
```

```{r Fig4,cache=TRUE, fig.width=6, fig.height=3}
ggplot(d1, aes(x=N, y=fitted, col=freq))+
  geom_point() +
  ylab("Estimated proportion of nulls") +
  guides(color=guide_legend(title="MAF in HapMap CEU population"))
```


### Session Information

```{r}
devtools::session_info()
```

