---
title: "Generate histograms in Figures 1, S5"
author: "Simina Boca, Jeff Leek"
date: "`r Sys.Date()`"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{swfdr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path='Figures/')
```

```{r style, echo = FALSE, results = 'asis'}
BiocStyle::markdown()
```

Load the relevant libraries:

```{r,message=FALSE}
library(readr)
library(dplyr)
library(fdrtool)
library(betareg)
library(splines)
library(Hmisc)
library(ggplot2)
library(IHW)
```

Load the .RData file with the BMI GIANT GWAS meta-analysis data:

```{r,cache=TRUE}
load("BMI_GIANT_GWAS.RData")
```

Generate histogram of p-values for all sample sizes and histogram of p-values for sample sizes < 200,000:

```{r Fig1,cache=TRUE, fig.width=9, fig.height=5}
par(mfrow=c(1,2))
hist(BMI_GIANT_GWAS$p, col="grey", main="All N", xlab="P-value")
hist(BMI_GIANT_GWAS$p[BMI_GIANT_GWAS$N < 200000], 
     col="grey", main="N < 200,000", xlab="P-value")
```

Do diagnostic plots as in \url{http://bioconductor.org/packages/release/bioc/vignettes/IHW/inst/doc/introduction_to_ihw.html#diagnostic-plots}:

```{r FigS5, fig.width=9, fig.height=5}
BMI_GIANT_GWAS$NGroup <- groups_by_filter(BMI_GIANT_GWAS$N,8)

table(BMI_GIANT_GWAS$NGroup)

ggplot(BMI_GIANT_GWAS, aes(x=p)) +
  geom_histogram(binwidth = 0.025, boundary = 0) +
  facet_wrap( ~ NGroup, nrow=2)

ggplot(BMI_GIANT_GWAS, aes(x=p)) +
  geom_histogram(binwidth = 0.025, boundary = 0) +
  facet_wrap( ~ Freq_MAF_Int_Hapmap, nrow=1)
```

### Session Information

```{r}
devtools::session_info()
```

